# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dds_tp.xdc

# IP: ip/blk_mem_triangular/blk_mem_triangular.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_triangular || ORIG_REF_NAME==blk_mem_triangular} -quiet] -quiet

# IP: ip/blk_mem_square/blk_mem_square.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_square || ORIG_REF_NAME==blk_mem_square} -quiet] -quiet
