# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Vivado/FPGA_Communicate_Base/lab1_DDS_Design/lab_dds_block_ram/lab_dds/lab_dds.srcs/sources_1/ip/blk_mem_sin/blk_mem_sin.xci
# IP: The module: 'blk_mem_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/FPGA_Communicate_Base/lab1_DDS_Design/lab_dds_block_ram/lab_dds/lab_dds.srcs/sources_1/ip/blk_mem_sin/blk_mem_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_sin'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/Vivado/FPGA_Communicate_Base/lab1_DDS_Design/lab_dds_block_ram/lab_dds/lab_dds.srcs/sources_1/ip/blk_mem_sin/blk_mem_sin.xci
# IP: The module: 'blk_mem_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Vivado/FPGA_Communicate_Base/lab1_DDS_Design/lab_dds_block_ram/lab_dds/lab_dds.srcs/sources_1/ip/blk_mem_sin/blk_mem_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
