set_property PACKAGE_PIN T2 [get_ports clk_50MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50MHz]

set_property PACKAGE_PIN H8 [get_ports {out_da_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[0]}]
set_property PACKAGE_PIN R8 [get_ports {out_da_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[1]}]
set_property PACKAGE_PIN K4 [get_ports {out_da_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[2]}]
set_property PACKAGE_PIN K3 [get_ports {out_da_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[3]}]
set_property PACKAGE_PIN J3 [get_ports {out_da_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[4]}]  
set_property PACKAGE_PIN K2 [get_ports {out_da_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[5]}]  
set_property PACKAGE_PIN J5 [get_ports {out_da_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[6]}]
set_property PACKAGE_PIN K5 [get_ports {out_da_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[7]}]
set_property PACKAGE_PIN N8 [get_ports {out_da_data_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[8]}]
set_property PACKAGE_PIN P8 [get_ports {out_da_data_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[9]}]
set_property PACKAGE_PIN K7 [get_ports {out_da_data_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[10]}]
set_property PACKAGE_PIN L7 [get_ports {out_da_data_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_da_data_0[11]}]

set_property PACKAGE_PIN J8 [get_ports DAC_A_B_s_0]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_A_B_s_0]
set_property PACKAGE_PIN K8 [get_ports da_cs_0]
set_property IOSTANDARD LVCMOS33 [get_ports da_cs_0]
set_property PACKAGE_PIN F2 [get_ports out_da_wr_0]
set_property IOSTANDARD LVCMOS33 [get_ports out_da_wr_0]

#set_property PACKAGE_PIN Y13 [get_ports led0]
#set_property IOSTANDARD LVCMOS33 [get_ports led0]

# set_property PACKAGE_PIN P3 [get_ports phase_data[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[7]]
# set_property PACKAGE_PIN P5 [get_ports phase_data[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[6]]
# set_property PACKAGE_PIN P6 [get_ports phase_data[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[5]]
# set_property PACKAGE_PIN M3 [get_ports phase_data[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[4]]
# set_property PACKAGE_PIN M4 [get_ports phase_data[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[3]]
# set_property PACKAGE_PIN R7 [get_ports phase_data[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[2]]
# set_property PACKAGE_PIN P7 [get_ports phase_data[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[1]]
# set_property PACKAGE_PIN W15 [get_ports phase_data[0]]
# set_property IOSTANDARD LVCMOS33 [get_ports phase_data[0]]

# set_property PACKAGE_PIN P2 [get_ports wen]
# set_property IOSTANDARD LVCMOS33 [get_ports wen]

set_property PACKAGE_PIN P3 [get_ports mux[1]]
set_property IOSTANDARD LVCMOS33 [get_ports mux[1]]
set_property PACKAGE_PIN P5 [get_ports mux[0]]
set_property IOSTANDARD LVCMOS33 [get_ports mux[0]]
